name: CI-Installer

on:
  push:
    branches:
    - master
    - release/*
    tags:
    - installer-*
  pull_request:
    branches:
    - master
    - release/*
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Configuration'
        required: true
        default: 'Release'
        type: choice
        options:
        - Release
        - Debug

env:
  CONFIGURATION: ${{ inputs.configuration != '' && inputs.configuration || 'Release' }}
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: 1
  INSTALLER_DOTNET_VERSION: '8.0'
  INSTALLER_PLATFORM: 'win-x64'

jobs:
  windows:
    runs-on: windows-latest

    steps:

    - name: Checkout 
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '${{ env.INSTALLER_DOTNET_VERSION }}.x'

    - name: "Set Publish Path"
      run: echo "PUBLISH_PATH=./Installer/bin/${{ env.CONFIGURATION }}/net${{ env.INSTALLER_DOTNET_VERSION }}/${{ env.INSTALLER_PLATFORM }}/publish/" >> $GITHUB_ENV        
      shell: bash
      
    - name: Build
      run: dotnet build -c ${{ env.CONFIGURATION }} ./Installer/Installer.csproj

    - name: Publish
      run: dotnet publish -c ${{ env.CONFIGURATION }} ./Installer/Installer.csproj

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Installer.exe
        path: ${{ env.PUBLISH_PATH }}Installer.exe

    - name: Zip
      if: startsWith(github.ref, 'refs/tags/')
      run: Compress-Archive -Path ${{ env.PUBLISH_PATH }}Installer.exe -Destination ./Installer.zip
      shell: powershell

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./Installer.zip
        make_latest: true
